name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: pytest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: src/requirements-dev.txt

      - name: Install dependencies
        working-directory: src
        run: pip install -r requirements-dev.txt

      - name: Run tests
        working-directory: src
        run: python -m pytest
